[package]
edition = "2024"
name = "proposer"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]
path = "src/proposer.rs"

[dependencies]
bincode = "1.3"
chrono = "0.4.41"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
wasi = "0.14.2"
wit-bindgen = "0.41"
