[package]
name = "wasi-keyvalue-component-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true, features = ["std"] }
wit-bindgen = { workspace = true, features = ["realloc", "macros"] }
