[package]
name = "runners"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmtime = "33"
wasmtime-wasi = "33"

[build-dependencies]
paxos-wasm-utils = { path = "../shared/utils" }
network-ws = { path = "../network-ws" }
agents = { path = "../agents" }
