[package]
name = "utils-wrpc_v2"
version = "0.2.0"
edition = "2021"

[lib]

[dependencies]
log = "0.4"
wit-bindgen = "0.39.0"
wit-bindgen-wrpc = "0.9.0"
anyhow = "1"
tracing-subscriber = "0.3.19"
# wrpc = "0.14.0"
