[package]
name = "network-server-tcp"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/network_server_tcp.rs"
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.42"
wasi = "0.14.2"
rand = "0.9"
