world proposer-world {
    import logger;

    export proposer;
}

world acceptor-world {
    import logger;

    export acceptor;
}

world learner-world {
    import logger;

    export learner;
}

world kv-store-world {
    import logger;

    export kv-store;
}

world leader-detector-world {
    import logger;
    
    export leader-detector;
}

world failure-detector-world {
    import logger;
    import leader-detector;

    export failure-detector;
}

world paxos-world {

    import proposer-agent;
    import acceptor-agent;
    import learner-agent;

    import failure-detector;

    /// Needs to be implemented by host
    import network;
    import logger; 

    export paxos-coordinator;
    // export proposer-agent;
    // export acceptor-agent;

}

// world paxos-client-world {
//     import paxos-coordinator;
//     export client;
// }

// world command-client-world {
//     import client;
// }


world proposer-agent-world {
    import proposer;
    import network;
    import logger;

    import failure-detector;

    export proposer-agent;
}

world acceptor-agent-world {
    import acceptor;
    import network;
    import logger;

    export acceptor-agent;
}

world learner-agent-world {
    import learner;
    import kv-store;
    import network;
    import logger;

    export learner-agent;
}

world serializer-world {
    // import logger;
    
    export serializer;
}

world ws-client-world {
    import serializer;

    import logger;

    export network;
}

world paxos-ws-world {
    import serializer;
    import proposer-agent;
    import acceptor-agent;
    import learner-agent;

    import logger;

    export ws-server;
}

world paxos-client-world {
    import serializer;

    // import logger;

    export paxos-client;
}

// TODO: Could instead import the ws-server directly inside the proposer-agent

world proposer-ws-world {
    import serializer;
    import proposer-agent;

    import logger;

    export ws-server;
}

world acceptor-ws-world {
    import serializer;
    import acceptor-agent;

    import logger;

    export ws-server;
}

world learner-ws-world {
    import serializer;
    import learner-agent;

    import logger;

    export ws-server;
}