[workspace]
resolver = "2"
members = [
    # "guest-adder-rs",
    # "guest-interfaced-adder-rs",
    "guest-kv-store-rs",
    # "host-command-component",
    "host-rs",
]

[workspace.dependencies]
wit-bindgen = "0.37.0"
