[package]
name = "paxos-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.10"
rand = "0.9.0"

[features]
default = ["basic"]
basic = []
advanced = []

[[bin]]
name = "paxos-rust"
path = "src/main.rs"
