// Generated by `wit-bindgen` 0.36.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod paxos {
        pub mod acceptor {
            #[allow(dead_code, clippy::all)]
            pub mod funcs {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_handleprepare_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::handleprepare(arg0 as u32, arg1 as u32);
                    let ptr1 = _RET_AREA.0.as_mut_ptr().cast::<u8>();
                    let (t2_0, t2_1) = result0;
                    *ptr1.add(0).cast::<u8>() = (match t2_0 {
                        true => 1,
                        false => 0,
                    }) as u8;
                    match t2_1 {
                        Some(e) => {
                            *ptr1.add(4).cast::<u8>() = (1i32) as u8;
                            let vec3 = (e.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *ptr1.add(12).cast::<usize>() = len3;
                            *ptr1.add(8).cast::<*mut u8>() = ptr3.cast_mut();
                        }
                        None => {
                            *ptr1.add(4).cast::<u8>() = (0i32) as u8;
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_handleprepare<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(4).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0.add(8).cast::<*mut u8>();
                            let l2 = *arg0.add(12).cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_handleaccept_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                    arg2: *mut u8,
                    arg3: usize,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg3;
                    let bytes0 = _rt::Vec::from_raw_parts(arg2.cast(), len0, len0);
                    let result1 = T::handleaccept(
                        arg0 as u32,
                        arg1 as u32,
                        _rt::string_lift(bytes0),
                    );
                    match result1 {
                        true => 1,
                        false => 0,
                    }
                }
                pub trait Guest {
                    fn handleprepare(id: u32, pnum: u32) -> (bool, Option<_rt::String>);
                    fn handleaccept(id: u32, pnum: u32, value: _rt::String) -> bool;
                }
                #[doc(hidden)]
                macro_rules! __export_paxos_acceptor_funcs_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[export_name =
                        "paxos:acceptor/funcs@0.1.0#handleprepare"] unsafe extern "C" fn
                        export_handleprepare(arg0 : i32, arg1 : i32,) -> * mut u8 {
                        $($path_to_types)*:: _export_handleprepare_cabi::<$ty > (arg0,
                        arg1) } #[export_name =
                        "cabi_post_paxos:acceptor/funcs@0.1.0#handleprepare"] unsafe
                        extern "C" fn _post_return_handleprepare(arg0 : * mut u8,) {
                        $($path_to_types)*:: __post_return_handleprepare::<$ty > (arg0) }
                        #[export_name = "paxos:acceptor/funcs@0.1.0#handleaccept"] unsafe
                        extern "C" fn export_handleaccept(arg0 : i32, arg1 : i32, arg2 :
                        * mut u8, arg3 : usize,) -> i32 { $($path_to_types)*::
                        _export_handleaccept_cabi::<$ty > (arg0, arg1, arg2, arg3) } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_paxos_acceptor_funcs_0_1_0_cabi;
                #[repr(align(4))]
                struct _RetArea([::core::mem::MaybeUninit<u8>; 16]);
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 16],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}
/// Generates `#[no_mangle]` functions to export the specified type as the
/// root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_acceptor_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::paxos::acceptor::funcs::__export_paxos_acceptor_funcs_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::paxos::acceptor::funcs);
    };
}
#[doc(inline)]
pub(crate) use __export_acceptor_impl as export;
#[cfg(target_arch = "wasm32")]
#[link_section = "component-type:wit-bindgen:0.36.0:paxos:acceptor@0.1.0:acceptor:encoded world"]
#[doc(hidden)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 281] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x9a\x01\x01A\x02\x01\
A\x02\x01B\x06\x01ks\x01o\x02\x7f\0\x01@\x02\x02idy\x04pnumy\0\x01\x04\0\x0dhand\
leprepare\x01\x02\x01@\x03\x02idy\x04pnumy\x05values\0\x7f\x04\0\x0chandleaccept\
\x01\x03\x04\0\x1apaxos:acceptor/funcs@0.1.0\x05\0\x04\0\x1dpaxos:acceptor/accep\
tor@0.1.0\x04\0\x0b\x0e\x01\0\x08acceptor\x03\0\0\0G\x09producers\x01\x0cprocess\
ed-by\x02\x0dwit-component\x070.220.0\x10wit-bindgen-rust\x060.36.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
