package paxos:learner@0.1.0

world learner {
    import acceptor {
        highest-accepted: func() -> (proposal_id: u64, value: string)
    }

    export learn {
        learn: func(proposal_id: u64, value: string)
    }
}
