package paxos:proposer@0.1.0

world proposer {
    import acceptor {
        prepare: func(proposal_id: u64) -> bool
        accept: func(proposal_id: u64, value: string) -> bool
    }

    export propose {
        propose: func(proposal_id: u64, value: string) -> bool
    }
}
