package simple-paxos-demo:proposer;

interface proposer {
    prepare: func(proposal_id: u64) -> bool;
    propose: func(proposal_id: u64, value: string) -> bool;
}

world proposer {
    export proposer;
    import paxos:acceptor/acceptor@0.1.0;
}
