[package]
edition = "2021"
name = "agents"
version = "0.1.0"

[features]
host_storage = []

[dependencies]

[build-dependencies]
core = { path = "../core" }
paxos-wasm-utils = { path = "../shared/utils" }
