# ─── config.yaml ────────────────────────────────────────

# logging
log_level: error    # "debug", "info", "warning", "error"

# all nodes in your entire deployment:
nodes:
  - node_id: 1
    address: "127.0.0.1:50051"
    role: "learner"
  - node_id: 2
    address: "127.0.0.1:50052"
    role: "acceptor"
  - node_id: 3
    address: "127.0.0.1:50053"
    role: "proposer"

  - node_id: 4
    address: "127.0.0.1:50054"
    role: "learner"
  - node_id: 5
    address: "127.0.0.1:50055"
    role: "acceptor"
  - node_id: 6
    address: "127.0.0.1:50056"
    role: "proposer"

  - node_id: 7
    address: "127.0.0.1:50057"
    role: "learner"
  - node_id: 8
    address: "127.0.0.1:50058"
    role: "acceptor"
  - node_id: 9
    address: "127.0.0.1:50059"
    role: "proposer"
  # - node_id: 1
  #   address: "127.0.0.1:50051"
  #   role: "learner"
  # - node_id: 2
  #   address: "127.0.0.1:50052"
  #   role: "learner"
  # - node_id: 3
  #   address: "127.0.0.1:50053"
  #   role: "acceptor"
  # - node_id: 4
  #   address: "127.0.0.1:50054"
  #   role: "acceptor"
  # - node_id: 5
  #   address: "127.0.0.1:50055"
  #   role: "acceptor"
  # - node_id: 6
  #   address: "127.0.0.1:50056"
  #   role: "proposer"
  # - node_id: 7
  #   address: "127.0.0.1:50057"
  #   role: "proposer"

# how those nodes are grouped into independent Paxos clusters
clusters:
  1: [1,2,3]

  2: [4,5,6]

  3: [7,8,9]

  # 1: [1]
  # 2: [2]
  # 3: [3]
  # 4: [4]
  # 5: [5]
  # 6: [6]
  # 7: [7]
  # 8: [8]
  # 9: [9]

# ─── run-loop tuning ───────────────────────────────────
run_config:
  is_event_driven: true
  acceptors_send_learns: true
  learners_send_executed: true
  prepare_timeout: 50
  demo_client: false
  demo_client_requests: 10000
  batch_size: 20
  tick_micros: 100
  exec_interval_ms: 100
  retry_interval_ms: 500
  learn_max_gap: 10
  executed_batch_size: 10
  client_server_port: 60000
  persistent_storage: false
  heartbeats: false
  heartbeat_interval_ms: 200
# TODO: add configs for crashing, and hot reloading nodes