# ─── global cluster settings ───────────────────────────
leader_id: 1

# full list of nodes and which paxos-role they have
nodes:
  - node_id: 1
    address: "127.0.0.1:50051"
    role: "learner"
  - node_id: 2
    address: "127.0.0.1:50052"
    role: "learner"
  - node_id: 3
    address: "127.0.0.1:50053"
    role: "acceptor"
  - node_id: 4
    address: "127.0.0.1:50054"
    role: "acceptor"
  - node_id: 5
    address: "127.0.0.1:50055"
    role: "acceptor"
  - node_id: 6
    address: "127.0.0.1:50056"
    role: "proposer"
  - node_id: 7
    address: "127.0.0.1:50057"
    role: "coordinator" # Last node has to be either "proposer" or "coordinator"

# ─── run-loop tuning ───────────────────────────────────
run_config:
  is_event_driven: true
  acceptors_send_learns: false
  learners_send_executed: false
  prepare_timeout: 1000
  demo_client: false
  tick_ms: 10
  client_server_port: 60000
