[package]
name = "acceptor-wrpc-v2"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
log = "0.4"
wit-bindgen = "0.38.0"
# wit-bindgen-wrpc = "0.9.0"
# wrpc = "0.14.0"
