package paxos:hosttest@0.1.0;

// interface adder {
//     add: func(a: u32, b: u32) -> u32;
// }

// world hosttest {
//     export adder;
// }

world hosttest {
    export add: func(a: u32, b: u32) -> u32;
}
